### ISSUE TITLE
create account requires private key

### ISSUE THREAD

**Issue by doc-l2** [kinecosystem/kin-node#1]
Hello,

I'd like to implement agora for kinwalletcreator.com, however I don't want people sending their secret to my server to create the account obviously.

When I look at the internals of this function here https://github.com/kinecosystem/kin-node/blob/24a8b819507ab1bdabac6ff4ba4da8716aa1a367/src/client/internal.ts#L79

It seems that the secret key is not required at all, the first line is to get the public key from the secret. 

Is it possible to change the function such that `createAccount` requires the public key instead of the private one?

Thanks!

**Comment by chaseeb** [comment]
So in the case of allowing users to generate their Keypair locally, only sending the public key to the server for security this makes complete sense. @mfycheng

**Comment by chaseeb** [comment]
Thanks for the note Luc. We're looking into it.

**Comment by doc-l2** [comment]
I want to close this issue. For other people that are reading this: it is like this because Solana will need the private key, so it has been made forwards-compatible.
