### ISSUE TITLE
Possible Issues with New NodeJS Documentation 

### ISSUE THREAD

**Issue by lvto2000** [kinecosystem/kin-node#18]
I recently received the pointer to the new NodeJS Getting Started with the Node SDK development documents (https://kintegrate.dev/tutorials/getting-started-node-sdk/).  After review and several unsuccessful hours/days of testing, there seem to be many issues with following that guidance as it is written.  The steps assume the reader will guess or reverse engineer the source code to figure out the missing steps to get it going.  As a examples: 

**2. Create a Node.js app and add the kin.ts class to your app**

There is no guidance in the document for how the best way to include that class.  One could assume that the tsc package needs to be installed and working, but there is no prerequisite list of extra node packages that must be included to indicate we need tsc.  In addition, depending on the operating system (Fedora 33 server in my case) tsc presents all kinds of issues because it must be globally installed vs. local.  I had to find that out the hard way as most folks assume local tsc package installs should work.  The end result of using tsc was 17 compile errors on that kin.ts file.  One could also assume that edits could be made to the package. json file to include {"target", "module"} to allow import of the ts file as is with no compile and the extension changed to js for nodejs.  But again, its not clear which path is best without instructions. 

Using either of those approaches does not provide a clear understanding of what should be required or imported after inclusion in my own test.js script.   As an example the very next step says the following:

**3. Instantiate a new Kin client**
**// Set up Kin client**
**const kin = new Kin(Environment.Test)**

How?  When did you tell me what to **require or import**  where?  Should I  have done any of the following?

**Kin = require('./kin.js')  OR, Import Kin as './kin.js'** 

In your instructions on the main kin_node githum site located here: https://github.com/kinecosystem/kin-node/tree/master/src.  You say do this:

**import {Client, Environment} from "@kinecosystem/kin-sdk-v2";**
**const client = new Client(Environment.Test);**

I realize that the NEW and improved instructions say use the kin.ts file and use Kin for the new kin, but the reason I mention this is the because of the following things I found. After a require or import of ./kin.js to Kin as a guess and proper assignment of kin to new Kin(Environment.Test).  I get the following nodejs error. 

**const kin = new Kin(Environment.Test)**
**ReferenceError: Environment is not defined**

After hours of digging through various pieces of your code located:

HERE: https://github.com/kinecosystem/kin-node/tree/master/examples/client
AND HERE: https://github.com/kintegrate/kin-starter-node/tree/main/src
AND HERE: https://github.com/kinecosystem/kin-node/tree/master/src

Then, compiling your various ts.files with errors and looking through the code there I managed to get some of the basic things working by reverse engineering what I saw in your source ts and compiled js files and coming up with things that worked somewhat.  After custom edits to my package.json file to allow us of import statements instead of requires statements, I ended up hacking the kin.ts file and taking what I needed to create my own test.js file by including the following in it: 

**import { Client, Environment, kinToQuarks, PrivateKey, PublicKey, TransactionType } from '@kinecosystem/kin-sdk-v2'**

This revealed that the main kin_node source code only exposes Client as an option.  So I used that in the workarounds I produced.  Also while tracking the original error down, I reviewed the source code outputs (kin.js) from the compile of the kin.ts file and found the following: 

**kin = new kin_1.Kin(kin_sdk_v2_1.Environment.Test);**

That is not anywhere close to the instructions provided in your new guide that says do the following once importing the kin.ts class:

**const kin = new Kin(Environment.Test)**

However creating my workaround via direct import of the exposed Environment method, I was able to execute most of the rest of your guide until I got to the requestAirDrop function.  The function provided in your guide does not match the declared function in your source which, requires a publicKey value vs. the Account object or array you specified in your original gitlab source located here: 

 **https://github.com/kinecosystem/kin-node/tree/master/src**

**console.log('Request Airdrop for Alice')
await kin.requestAirdrop(balancesAlice[0], '10')**

balanceAlice[0] in this case throws an error stating that the 0 is invalid.  balanceAlice alone throws and error stating that the Account or Key information is incorrect.  I reviewed the source code in the kin_node source and found that the original method declaration for requestAirdrop() requires the PublicKey.   I also initially experienced  an error at line 450 of /var/www/NODE_JS/kin-node-master/node_modules/@kinecosystem/kin-sdk-v2/dist/client/internal.js  where running the function produced an error for req.setQuarks(quarks.toNumber()) stating that **quarks.toNumber** does not exist.  I later found that  **toNumber** is not even a function to be used in this way. 

Understanding the issue I changed that line to the following just to see if everything else would work:

**var quarkserror = "quarks value needs to be number";
Number(quarks)? req.setQuarks(quarks) : quarkserror;**

I got that section to work then got a series of "Account doesn't Exist" errors when attempting to run the requestAirDrop method.   I could not get that issue resolved using my own code.

I also forgot to mention earlier that Step 4 also fails.  Here is how it reads:

**4. Create account for Alice
const privateKeyAlice = Kin.generateKey()**

In the source code located here **https://github.com/kinecosystem/kin-node/tree/master/src**  there is no function that exists anywhere with that name (searched entire source code directory using grep generateKey * -R).  The function does not exist.  Even in your kin.ts or resulting tsc compiled kin.js file there is no reference to generateKey in the context of creating a new user account and key pair. There is reference to the .generateKey and .random().  I see that there is an exported method in the Kin class under kin.ts called generateKey.  I am assuming that the tsc errors produced at compile time did not allow generation of that method in my final kin.js file. 

Finally I read at the bottom of your guide page regarding the quick startup files.  I downloaded the nodejs quickstart up source code located here: https://github.com/kintegrate/kin-starter-node/tree/main/src.  Again, there were no instructions or guide as to how I should use them.  Again, I had to guess that I should use tsc to compile them into nodejs usable form.  Again, I received plenty of errors.  However, this time when I ran the index.js file using node everything worked ok, but it ran a tight set of related scripts in a specified order.  So that means, I am still going to have to dig through the source code in those compiled *.js files to figure out the right function calls to use what you created for my own app.  So far, they do not seem to match up in any way to the NEW or OLD guide you provided. 

Did I miss something in the documents you provided or are there a new ones coming?

**Comment by beeman** [comment]
@lvto2000 thanks for writing this up. Please provide any feature issues with Kintegrate.dev to the repo https://github.com/kintegrate/kintegrate.dev as it's not about the sdk.

However, from reading your post I feel like there might be some assumptions about the level of knowledge from the developer we expect, and have not made explicit - this is my fault. 

We expect the developer to have decent working experience with the specific tech  they pick. You should for instance never have to compile anything manually, nor run tsc manually. 

I'm sorry this has cost you hours or days, that's what we try to avoid. I invite you to join the Discord linked on https://kintegrate.dev and ask questions in the kin-node channel. 

That way we can help you better buy guiding you along the way, and pointing to resources that might help cover the base knowledge of using Node with TypeScript.

**Comment by lvto2000** [comment]
Hmmm...  Well, I still got it working being the lowly programmer that I am.  :-)  I appreciate your graciousness in owning the issue nonetheless.  I will readily concede that I am not among the cool kid Principle Software Developers for nodejs.  However, I have been programming in various languages for over 30 years.  With that in mind and now that I have it working, there are some fairly simple steps that could be added to your guide that will assist **all levels of programmers** in understanding what should be simple starter examples in my mind.  

As a potential business who might use Kin, I would expect all of my programming folks to at least be able to get your basic API examples working with minimal effort and knowledge.  That's why you developed them I would hope.   As an example (pun intended), to elect to use TypeScript vs nodejs's for such a small code stack (learning examples) seems like a bit of  ostentation even for the nodejs cool kids.  Conversely, selecting a scripting language with that level of meticulousness and complexity vs pure JavaScript, would make interested users assume that same level of detail would be followed with the guides to support it.     

Again, I appreciate you owning the issue.  Still, as a Kin holder it is terrifyingly sobering to know that this is what potential companies and curious users/programmers of kin's API may be experiencing and not saying anything or anything good to folks who want to know about Kin's interoperability in their business models.   I think the **"assumptions about the level of knowledge from the developer [you] expect"** are not good for this purpose.   Just my 2 cents, but I strongly recommend that you take ALL the guides that you posted thus far.   They should never see the light of day until the new documentation is fully complete and thoroughly tested by folks not close to your direct DevOps group and devoid of the usual "advanced" programmer assumptions that usually come with the cool kids way of thinking vs the Kin business's bottom line.  I don't need hand holding on Discord to know that.   Appreciate the offer though.

**Comment by beeman** [comment]
@lvto2000 I'm sorry to hear you feel this way. Others have praised the new docs as it was 'exactly what they were looking for'. So to each their own I guess.

**Comment by lvto2000** [comment]
Yes I am fully aware of the echo chamber and fan boys who are exist on Reddit, Discord and other Kin communities.  Believe it or not, I am here to help from a different perspective. 

Again, I appreciate your graciousness in trying to find a solution.  Just forgive me if I am not completely loving all of it. :-)

**Comment by lvto2000** [comment]
Your package.json file that looks as if it requires the same tsc program (highlighted below) I used to compile the js code that worked.  Interesting.  Got mine to work before in your kin-starter-node directory before I found this, then I moved that file to the kin_node_master where it wasn't working.  Then  I ran npm install.  Now it works in that directory too.   So I am not sure I agree with this statement "**You should for instance never have to compile anything manually, nor run tsc manually.**" However, I was never supplied an alternative method even in your last post.   

This package.json file for notes if I or some other poor soul need to reference later. 
{
  "name": "kin-starter-node",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "ts-node-dev --respawn src/index.ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Bram Borggreve",
  "license": "ISC",
  "devDependencies": {
    "@kinecosystem/kin-sdk-v2": "^0.5.0",
    "@types/bs58": "^4.0.1",
    "@types/node": "14",
    "bs58": "^4.0.1",
    "**ts-node-dev**": "^1.1.1",
    "**typescript**": "^4.1.5"
  },
  "dependencies": {
    "@kinecosystem/agora-api": "^0.26.1"
  }
}
