### ISSUE TITLE
Update readme import

### ISSUE THREAD

**Issue by doc-l2** [kinecosystem/kin-node#4]
The readme says:

`import {Client, Environment} from "@kinecosystem/kin-node";`

But it should be

`import {Client, Environment} from "@kinecosystem/kin-sdk-v2";`

I tried to create a pull request but all I did was fork it and then my change was gone, sometimes I don't get github (:

**Comment by kikengineering** [comment]
Good catch, fixed in: https://github.com/kinecosystem/kin-node/commit/f789b262b949e49b65e8d189b1db318e5f0e0e39
