### ISSUE TITLE
Update webhooks docs to show what request is actually done

### ISSUE THREAD

**Issue by doc-l2** [kinecosystem/kin-node#7]
It would be very helpful is the webhook documentation in the README actually showed what request is done with what parameters (ie: a GET or POST request with this and that querystring / body) instead of an express example. I don't use express so I now have to do trial and error to get the correct response.

Thanks!

**Comment by doc-l2** [comment]
ah I now see that there is a swagger doc. Might be helpful to link from the github readme to the docs :)

**Comment by chaseeb** [comment]
was this resolved?

**Comment by doc-l2** [comment]
Not really, but I'll close this and merge with https://github.com/kinecosystem/kin-node/issues/7
